[project]
name = "aegis-vault"
description = "A decentralized credit protocol with self-repaying loans."
authors = []
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token"

[[project.requirements]]
contract_id = "ST2NJZE3SPW0GCPC0YE4V805HTSAGNQJF1HXT6PKY.sip-010-v1"

[[project.requirements]]
contract_id = "ST2NJZE3SPW0GCPC0YE4V805HTSAGNQJF1HXT6PKY.aeusd-v2"

[[project.requirements]]
contract_id = "ST2NJZE3SPW0GCPC0YE4V805HTSAGNQJF1HXT6PKY.oracle-v2"

[contracts.vault-v2]
path = "contracts/vault.clar"
clarity_version = 2
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
