[project]
name = "aegis-vault"
description = "A decentralized credit protocol with self-repaying loans."
authors = []
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token"

[[project.requirements]]
contract_id = "SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-oracle-v4"

[[project.requirements]]
contract_id = "SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-storage-v4"

[contracts.aegis-sip10-v3]
path = "contracts/aegis-sip-010.clar"
clarity_version = 2
epoch = "latest"

[contracts.aegis-aeusd-v3]
path = "contracts/aegis-aeusd.clar"
clarity_version = 2
epoch = "latest"

[contracts.aegis-oracle-v3]
path = "contracts/aegis-oracle.clar"
clarity_version = 2
epoch = "latest"

[contracts.aegis-vault-v4]
path = "contracts/aegis-vault.clar"
clarity_version = 2
epoch = "latest"
depends_on = ["aegis-sip10-v3", "aegis-oracle-v3", "aegis-aeusd-v3"]

[contracts.aegis-auto-repay-v4]
path = "contracts/aegis-auto-repay.clar"
clarity_version = 2
epoch = "latest"
depends_on = ["aegis-vault-v4"]

[contracts.aegis-lp-token-v3]
path = "contracts/aegis-lp-token.clar"
clarity_version = 2
epoch = "latest"

[contracts.aegis-pool-v6]
path = "contracts/aegis-pool.clar"
clarity_version = 2
epoch = "latest"

[contracts.mock-btc-v4]
path = "contracts/mock-btc.clar"
clarity_version = 2
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
