[project]
name = "aegis-vault"
description = "A decentralized credit protocol with self-repaying loans."
authors = []
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token"

[contracts.aegis-sip10-v3]
path = "contracts/aegis-sip-010.clar"
clarity_version = 2
epoch = "latest"

[contracts.aegis-aeusd-v20]
path = "contracts/aegis-aeusd.clar"
clarity_version = 2
epoch = "latest"

[contracts.aegis-vault-v20]
path = "contracts/aegis-vault.clar"
clarity_version = 2
epoch = "latest"
depends_on = ["aegis-sip10-v3", "aegis-aeusd-v20"]

[contracts.aegis-auto-repay-v20]
path = "contracts/aegis-auto-repay.clar"
clarity_version = 2
epoch = "latest"
depends_on = ["aegis-vault-v20"]

[contracts.aegis-lp-token-v20]
path = "contracts/aegis-lp-token.clar"
clarity_version = 2
epoch = "latest"

[contracts.aegis-pool-v20]
path = "contracts/aegis-pool.clar"
clarity_version = 2
epoch = "latest"
depends_on = ["aegis-sip10-v3", "aegis-aeusd-v20", "aegis-lp-token-v20"]

[contracts.mock-btc-v5]
path = "contracts/mock-btc.clar"
clarity_version = 2
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
