[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_STACKS_NETWORK = "testnet"
  NEXT_PUBLIC_CONTRACT_ADDRESS = "ST2NJZE3SPW0GCPC0YE4V805HTSAGNQJF1HXT6PKY"
  NEXT_PUBLIC_VAULT_CONTRACT = "aegis-vault-v20"
  NEXT_PUBLIC_AEUSD_CONTRACT = "aegis-aeusd-v20"
  NEXT_PUBLIC_ORACLE_CONTRACT = "none"
  NEXT_PUBLIC_SBTC_CONTRACT = "mock-btc-v5"
  NEXT_PUBLIC_LP_TOKEN_CONTRACT = "aegis-lp-token-v21"
  NEXT_PUBLIC_POOL_CONTRACT = "aegis-pool-v21"
  NEXT_PUBLIC_IS_SUBNET = "false"
