[network]
name = "testnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "slow parrot else subject offer donkey case tip proud sunset slab pause patrol human raw will useless ill skate book drastic siren palace math"
# balance = 100_000_000_000_000

[testnet]
# stacks_node_rpc_address = "https://api.testnet.hiro.so"
# stacks_node_p2p_address = "testnet.hiro.so:20444"
